### ISSUE TITLE
500 Error 0Issue on install with EventListener/AssetSubscriber.php

### ISSUE THREAD

**Issue by TornMarketing** [mtcextendee/mautic-grapejs-bundle#1]
Getting this error on install

Mautic Version v2.15.1
PHP Version 7.0.33-0ubuntu0.16.04.5

`[2019-06-13 16:39:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getIntegrationSettings() on boolean" at /home/admin/web/domain.com.au/public_html/plugins/MauticGrapeJsBundle/EventListener/AssetSubscriber.php line 51 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getIntegrationSettings() on boolean at /home/admin/web/domain.com.au/public_html/plugins/MauticGrapeJsBundle/EventListener/AssetSubscriber.php:51)"} []
`

**Comment by coopergarry** [comment]
run php app/console mautic:plugins:reload
