### ISSUE TITLE
How to enable

### ISSUE THREAD

**Issue by larbous** [mtcextendee/mautic-grapejs-bundle#3]
I followed the steps and the plugin appeared in the list, but when I click opens a window with the logo just no options to activate. Is that so?
![Captura de Tela 2019-10-01 às 16 07 30](https://user-images.githubusercontent.com/1202326/65992460-a6a26080-e465-11e9-8645-b242df3e7484.png)

**Comment by kuzmany** [comment]
Nope. Try clear cache (app/cache/prod/) and again.

**Comment by larbous** [comment]
I've cleared But not works! I'm using v2.15.2. Is there something that I can make to see any error?

**Comment by larbous** [comment]
I still can't enable it. Any tips?

**Comment by larbous** [comment]
I reinstalled and now it's working.
