### ISSUE TITLE
Wrong file path in builder /index.php/media/images/grapesjs/

### ISSUE THREAD

**Issue by TornMarketing** [mtcextendee/mautic-grapejs-bundle#6]
Hey mate

Playing again with the plugin
Getting the wrong file path in builder, adding in /index.php/

/index.php/media/images/grapesjs/

Also is there an ability to manage the upload assets into folders?

**Comment by TornMarketing** [comment]
All good, was related to rewrite on the new installation
Found that the Site URL was /index.php on the default install

**Comment by fagnerdireito** [comment]
+1

**Comment by kuzmany** [comment]
This plugin is not supported anymore.
Go to official repo for Mautic released in 3.3.0
https://github.com/mautic/plugin-grapesjs-builder
