### ISSUE TITLE
Manual installation shows no plugin under /s/plugins/reload

### ISSUE THREAD

**Issue by ryanisonic** [mtcextendee/mautic-grapejs-bundle#7]
Hi there I have installed this as per the manual instructions.

The folder:
public_html/plugins/MauticGrapeJsBundle (permissions 755 )

I have unzipped to this directly to that folder ( MauticGrapeJsBundle.php exists under this folder )

No new plugins show to be enabled.

![image](https://user-images.githubusercontent.com/30221778/71220393-1234f500-2314-11ea-8d13-bb04fc8d3e93.png)

**Comment by kuzmany** [comment]
Clear cache
app/cache/prod/
